### ISSUE TITLE
设计上似有不合理

### ISSUE THREAD

**Issue by duzhipeng** [QQOQ/vue-social-captcha#1]
针对的是： url="http://pay.test.com/admin/captcha/"

特别的，针对Vue，一般靠取环境配置决定开发环境、测试环境、生产环境的后端地址，并不写死在像这样的地方，靠axios时，也是Vue初始化的时候就拿到这个地址了，不用组件间传递。所以你这里url需要这样指定，并且必须，这是第一个不合理的地方，因为这个URL需要不停手动变或者我专门加逻辑方便这里取到正确的URL。

如果按照你这个逻辑，以腾讯验证码为例，我拿到票据和相关信息后，这里vue-social-captcha会向后端发一次GET请求，而这时按照你的想法后端应该请求腾讯进行验证，并返回验证结果（0或者1）。然后前端可以继续进行下一步的业务。这就没意义了，因为我直接请求登录接口，绕过验证码接口。为避免这样，我又必须附加业务逻辑，在vue-social-captcha返回自己服务的一个验证票据，之后连同登录信息再上报后端，后端再验证。这就多余了，这是第二个不合理的地方。

我认为正确的做法，哥们你这个插件即然是只管验证码的，我建议纯粹一些，url参数这个不要了，vue-social-captcha只需要保留回调函数就好，使用者自己在回调函数里实现后续逻辑。vue-social-captcha不要有和后端交互的逻辑，不然太不灵活。

哥们你看呢？

**Comment by duzhipeng** [comment]
活着url改为回调一个方法，可以让用户自定义和后端的请求方式，也是非常好的。

**Comment by QQOQ** [comment]
> 针对的是： url="http://pay.test.com/admin/captcha/"
> 
> 特别的，针对Vue，一般靠取环境配置决定开发环境、测试环境、生产环境的后端地址，并不写死在像这样的地方，靠axios时，也是Vue初始化的时候就拿到这个地址了，不用组件间传递。所以你这里url需要这样指定，并且必须，这是第一个不合理的地方，因为这个URL需要不停手动变或者我专门加逻辑方便这里取到正确的URL。
> 
> 如果按照你这个逻辑，以腾讯验证码为例，我拿到票据和相关信息后，这里vue-social-captcha会向后端发一次GET请求，而这时按照你的想法后端应该请求腾讯进行验证，并返回验证结果（0或者1）。然后前端可以继续进行下一步的业务。这就没意义了，因为我直接请求登录接口，绕过验证码接口。为避免这样，我又必须附加业务逻辑，在vue-social-captcha返回自己服务的一个验证票据，之后连同登录信息再上报后端，后端再验证。这就多余了，这是第二个不合理的地方。
> 
> 我认为正确的做法，哥们你这个插件即然是只管验证码的，我建议纯粹一些，url参数这个不要了，vue-social-captcha只需要保留回调函数就好，使用者自己在回调函数里实现后续逻辑。vue-social-captcha不要有和后端交互的逻辑，不然太不灵活。
> 
> 哥们你看呢？

1、首先感谢你的建言，我不是很明白你的意思，这个url你可以是一个变量，可以放置在任何你习惯的配置文件里，这里引入url变量就行了，并不是写死的啊。
2、绕过验证码这里属于后端的了，比如前端发送了请求到服务端时，服务端可以用session来记录当前请求对象是否验证成功，如果没有验证那么接口就返回相应错误码，像登录接口后端必然要做这个事情的，不然可以无限请求，怎么做这个属于后端业务了

**Comment by duzhipeng** [comment]
嗯，你看，是这样：
1、URL肯定可以是一个变量，这没毛病。我换个方式说，比如你这里URL虽然可以是变量，但是是一个GET方法，假设我不想使用GET方法而改为POST时，你这样的限制局限性就出来了。
2、没错，你说的就是我说的第二段话的意思。为了匹配你插件的程序模式，通过你插件上来的GET经验证后，我可以再下发一个session匹配客户端，验证用户名和密码时一同校验。但这多了一步客户端请求不是吗？难道不可以客户端验证完成后，直接一次性携带验证码返回的票据、用户名、密码，一起给后端。后端先和验证码服务端通信验证票据正确性，通过后再验证用户名和密码。比起使用你的插件，少一次客户端请求，这体验会不会更好一些？这样后端也少写session部分的逻辑代码，皆大欢喜的事情。

极验的验证码没使用过，我猜测是不是那边的业务逻辑导致你是这样的设计。

简单点说，如果你的插件允许使用者重新定义URL做的事情，会更加通用和方便。

**Comment by duzhipeng** [comment]
另外你还指定了后端必须返回的数据和数据格式，这也是耦合了后端，其实没必要不是吗？你看你上面也谈到有些事情后端做就好，但这里又牵扯了后端的内容，又些矛盾。

**Comment by QQOQ** [comment]
> 嗯，你看，是这样：
> 1、URL肯定可以是一个变量，这没毛病。我换个方式说，比如你这里URL虽然可以是变量，但是是一个GET方法，假设我不想使用GET方法而改为POST时，你这样的限制局限性就出来了。
> 2、没错，你说的就是我说的第二段话的意思。为了匹配你插件的程序模式，通过你插件上来的GET经验证后，我可以再下发一个session匹配客户端，验证用户名和密码时一同校验。但这多了一步客户端请求不是吗？难道不可以客户端验证完成后，直接一次性携带验证码返回的票据、用户名、密码，一起给后端。后端先和验证码服务端通信验证票据正确性，通过后再验证用户名和密码。比起使用你的插件，少一次客户端请求，这体验会不会更好一些？这样后端也少写session部分的逻辑代码，皆大欢喜的事情。
> 
> 极验的验证码没使用过，我猜测是不是那边的业务逻辑导致你是这样的设计。
> 
> 简单点说，如果你的插件允许使用者重新定义URL做的事情，会更加通用和方便。

明白你的意思了，这个确实是，或者你看我这样重新改动，可以选择get或者是post提交，还可以加入自定义参数提交，这样就解决你说的问题了，就不需两次数据验证了
。。。
极验验证跟腾讯验证还真不一样，极验是初始化的时候就请求服务端，腾讯是滑动验证码正确后才提交请求，像我上面说的设计就不合理了

**Comment by duzhipeng** [comment]
谢谢大神的回复，我理解了。其实极验的这种要求，建议URL参数为它服务就好。腾讯的还是可以自定义回调函数。
我这边先用了https://github.com/NineSwordsMonster/vue-tencent-captcha 。这个比较符合我目前的需求，这里给出来仅供你参考。
